eps_angle: 6.0
distance_threshold: 0.05
tol_superq: 0.000001
optimizer_points: 800
random_sampling: true
max_iter: 10000000
minimum_points: 400
fraction_pc: 4
threshold_axis: 0.8
threshold_section1: 0.7
threshold_section2: 0.3
object_class: "default"
single_superq: true
merge_model: true
th_points: 100
