eps_angle: 6.0
distance_threshold: 0.005
tol_superq: 0.0001
optimizer_points: 1000
random_sampling: true
max_iter: 100000000
minimum_points: 800
fraction_pc: 6
threshold_axis: 0.8
threshold_section1: 0.7
threshold_section2: 0.3
object_class: "default"
single_superq: true
merge_model: true
th_points: 100
