initial_state:
  head_controller:
    pan: 0.0  # Initial pan angle for the head in radians
    tilt: -0.55  # Initial tilt angle for the head in radians

  torso_controller:
    height: 0.3  # Initial height for the torso lift in meters

initial_nav_to_pick:
  position: 
      x: 1.8879959441123082
      y: 0.6017079093591774
      z: 0.0
  orientation: 
      x: 0.0
      y: 0.0
      z: 0.5858055284381024
      w: 0.8104516536175095
      
robot_table:
    dimensions: [1.48, 3.0, 0.74]
    pose:
        position:
            x: 1.0
            y: 0.0
            z: 0.3
        orientation:
            x: 0.0
            y: 0.0
            z: 0.0
            w: 1.0


