use_glasses: false
use_asr: true
reaching_distance: 0.12
elimit1: 0.2
elimit2: 0.7
inflate_size: 0.035
max_error_joints: 0.01
head_joints_position_init: [0, -0.68]
torso_joint_position_init: 0.38
right_arm_joints_position_init: [-1.11, 1.15, 2.53, 1.59, -1.6, 1.25, 0.0]
left_arm_joints_position_init: [-1.11, 1.15, 2.53, 1.59, -1.6, 1.25, 0.0]
table_dimensions: [1.42, 3.0, 0.72]
table_position: [1.1,0.0,0.36]
table_dimensions2: [5.0, 1.5, 1.6]
table_position2: [0.5, -1.5, 0.3]
table_dimensions3: [5.0,1.5,2.0]
table_position3: [0.5, 1.5, 0.3]
threshold_plan_trajectory: 0.2
threshold_execute_trajectory: 0.5
goal_joint_tolerance: 0.011
left_gripper_position_difference_wrt_default: [0.033, 0.033]
right_gripper_position_difference_wrt_default: [0.033, 0.027]
init_demo_verbal_message: "Hey there! We've got some yummy cereal and cool milk on the table. Which one do you want first?"
milk_first_verbal_message: "Milk it is! Let's get that for you."
cereal_first_verbal_message: "Cereal it is! Let's get that for you."
pass_object_verbal_message: "Here you are!"
milk_second_verbal_message: "Alright, now I'll get the milk for you."
cereal_second_verbal_message: "Alright, now I'll get the cereal for you."

end_demo_verbal_message: "All done! Your cereal and milk are all set. Enjoy!"
user_id: 100
