robot_table:
    dimensions: [1.48, 3.0, 0.72]
    pose:
        position:
            x: 1.15
            y: 0.0
            z: 0.3
        orientation:
            x: 0.0
            y: 0.0
            z: 0.0
            w: 1.0
