# ObjectManipulation.action

# Define the goal
string task  # hand_over_to_person, move_object_next_to_person, pour_into, push_object_to_person
string object_for_task_name1
string object_for_task_name2 # Only used in the pour_into task
string[] object_names
geometry_msgs/Pose[] object_poses
shape_msgs/SolidPrimitive[] object_shapes

geometry_msgs/Point[] zone_place # Only used in the move_object_next_to_person task
---
# Define the result
bool success
string message
string arm_name # Arm that executed the task (left or right)

---
# Define the feedback
string status
int32 percent_complete
